### ISSUE TITLE
Disabling DCE fixes: 'HxOverrides' has no attribute 'arrayGet'

### ISSUE THREAD

**Issue by royalstream** [andyli/pyextern#1]
I was getting this error every single time:

```
Traceback (most recent call last):
  File "Main.py", line 4547, in <module>
    pyextern_Main.main()
  File "Main.py", line 3188, in main
    main.processModule(modname1,modname1)
  File "Main.py", line 2930, in processModule
    proc.processModule(module,moduleName,self)
  File "Main.py", line 3453, in processModule
    td2 = main.getTd(moduleName,"")
  File "Main.py", line 3052, in getTd
    _g22 = HxOverrides.arrayGet(Reflect.field(td,"meta"), 0)
AttributeError: type object 'HxOverrides' has no attribute 'arrayGet'
```

After doing some google research I found out it could be related to DCE.
I added `"-dce no"` to **build.hxml** and that seems to fix it but I'm still opening an issue because I suspect this could be related to my specific environment, I'm using Anaconda on Mac OS X.

**Comment by andyli** [comment]
Thanks for the report!
Indeed there is a dce issue in haxe 3.2.1, so I just added `-dce no` to workaround it.
FYI, the issue is apparently fixed in haxe since I couldn't reproduce it with a git build.
