### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by MolassesLover** [andyli/pyextern#25]
What terms is this project licensed under?

**Comment by andyli** [comment]
The Unlicense
https://github.com/andyli/pyextern/commit/1c7b226c7eef05b24711d637e56fe7ebea3b9868

**Comment by MolassesLover** [comment]
> The Unlicense [1c7b226](https://github.com/andyli/pyextern/commit/1c7b226c7eef05b24711d637e56fe7ebea3b9868)

Thank you! Always thankful for an open license like that.
