### ISSUE TITLE
How about add blender python api extern?

### ISSUE THREAD

**Issue by sonygod** [andyli/pyextern#8]
how about add blender python api extern?

**Comment by melMass** [comment]
Here is my untested attempt, I'm testing it soon but if you want to try and report :)
[blender-2.82.zip](https://github.com/andyli/pyextern/files/4246378/blender-2.82.zip)

**Comment by sonygod** [comment]
@melMass ,thank you for your work!

I used blender as a render engine for my Unity  app before,I'll check if I had time.

**Comment by melMass** [comment]
> Hiya, how did you go about making this?

Hey, it was 4 years ago so hard to tell, but your poke made me realize Haxe was still a thing 😅 . 
So I just tried following the readme's instruction, roughly:
```nushell

# python venv
uv venv -p 3.11 --seed
overlay use .venv/bin/activate.nu

# install python deps
uv pip install -r requirements.txt
uv pip install bpy

# install haxe dependencies
haxelib build.hxml

# build it
haxe build.hxml

# you now have the bindings generator as Main.py
python main.py bpy out
# saved in out/bpy
```

Here is **4.2.0** (*Still not tested*):
- [bpy-4.2.0.zip](https://github.com/user-attachments/files/16553495/bpy-4.2.0.zip)

**Comment by MolassesLover** [comment]
Oh that makes a lot of sense! I didn't know Blender was available through PyPi. Thank you so much for the help!
